version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "{{cookiecutter.author_github_username}}"
    default_labels:
      - "dependencies"{% if cookiecutter.use_docker == "y" %}
    - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "{{cookiecutter.author_github_username}}"
    default_labels:
      - "dependencies"{% endif %}
